# Generated by Django 6.1.1 on 2026-09-24 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='emtry',
            new_name='Entry',
        ),
    ]
